client_config_file: client_secrets.json
client_config:
  client_id: 965982350332-0dkqlvc077mqj195854knchg9cmbtf22.apps.googleusercontent.com
  client_secret: xX81TgA8VOtRhiP96d0kuHoS

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install