"""
    This module defines model's state_dict keys matches when trying to load an extern pretrained model.
    **NOTE:** these dictionnaries are subject oriented and this module is not generic.
"""
import re
CSRNet_DICT_MATCH={
    'CCN.output_layer.weight':'output_layer.weight',
'CCN.output_layer.bias':'output_layer.bias',
'CCN.frontend.0.weight':'frontEnd.0.weight',
'CCN.frontend.0.bias':'frontEnd.0.bias',
'CCN.frontend.2.weight':'frontEnd.2.weight',
'CCN.frontend.2.bias':'frontEnd.2.bias',
'CCN.frontend.5.weight':'frontEnd.5.weight',
'CCN.frontend.5.bias':'frontEnd.5.bias',
'CCN.frontend.7.weight':'frontEnd.7.weight',
'CCN.frontend.7.bias':'frontEnd.7.bias',
'CCN.frontend.10.weight':'frontEnd.10.weight',
'CCN.frontend.10.bias':'frontEnd.10.bias',
'CCN.frontend.12.weight':'frontEnd.12.weight',
'CCN.frontend.12.bias':'frontEnd.12.bias',
'CCN.frontend.14.weight':'frontEnd.14.weight',
'CCN.frontend.14.bias':'frontEnd.14.bias',
'CCN.frontend.17.weight':'frontEnd.17.weight',
'CCN.frontend.17.bias':'frontEnd.17.bias',
'CCN.frontend.19.weight':'frontEnd.19.weight',
'CCN.frontend.19.bias':'frontEnd.19.bias',
'CCN.frontend.21.weight':'frontEnd.21.weight',
'CCN.frontend.21.bias':'frontEnd.21.bias',
'CCN.backend.0.weight':'backEnd.0.weight',
'CCN.backend.0.bias':'backEnd.0.bias',
'CCN.backend.2.weight':'backEnd.2.weight',
'CCN.backend.2.bias':'backEnd.2.bias',
'CCN.backend.4.weight':'backEnd.4.weight',
'CCN.backend.4.bias':'backEnd.4.bias',
'CCN.backend.6.weight':'backEnd.6.weight',
'CCN.backend.6.bias':'backEnd.6.bias',
'CCN.backend.8.weight':'backEnd.8.weight',
'CCN.backend.8.bias':'backEnd.8.bias',
'CCN.backend.10.weight':'backEnd.10.weight',
'CCN.backend.10.bias':'backEnd.10.bias'
}